/**
 * config.yaml -> src/config.data.ts
 *
 * config.yaml stays authoritative so that adding a series remains a config
 * edit, the way CONTRIBUTING.md intends. Workers have no filesystem, so the
 * YAML is baked into a typed module at build time instead of parsed at runtime.
 *
 * Run: pnpm gen:config
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { parse } from "yaml";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(here, "..");

const raw = parse(readFileSync(path.join(root, "config.yaml"), "utf8"));

// db_path is a Python-collector concern: D1 is a binding, not a file path.
delete raw.db_path;

// Defaults that config.py applies while loading, applied here instead so the
// emitted module matches the Config type exactly.
raw.defi.morpho_graphql ??= "https://blue-api.morpho.org/graphql";
raw.defi.morpho_first ??= 25;

const banner = `/**
 * GENERATED by scripts/gen-config.mjs from config.yaml. Do not edit.
 * Run \`pnpm gen:config\` after changing config.yaml.
 */
import type { Config } from "./config";

export const config: Config = `;

writeFileSync(
  path.join(root, "src/config.data.ts"),
  `${banner}${JSON.stringify(raw, null, 2)};\n`,
);

const counts = {
  indexes: raw.indexes.length,
  bonds: raw.bonds.length,
  cb_rates: raw.cb_rates.length,
  series: raw.series.length,
  cycle_series: raw.cycle_series.length,
  cycle_tabs: raw.cycle_tabs.length,
  feeds: raw.feeds.length,
};
console.log("wrote src/config.data.ts", counts);
