/**
 * GENERATED by scripts/gen-config.mjs from config.yaml. Do not edit.
 * Run `pnpm gen:config` after changing config.yaml.
 */
import type { Config } from "./config";

export const config: Config = {
  "calendar_url": "https://nfs.faireconomy.media/ff_calendar_thisweek.json",
  "max_news": 15,
  "cadences": {
    "equity": 300,
    "bonds": 3600,
    "macro": 3600,
    "news": 600,
    "defi": 900,
    "midnight": 900,
    "refs": 900,
    "refs_history": 86400,
    "morpho": 900,
    "cycle": 86400
  },
  "indexes": [
    {
      "symbol": "SPX",
      "name": "S&P 500",
      "yahoo": "^GSPC"
    },
    {
      "symbol": "NDX",
      "name": "Nasdaq 100",
      "yahoo": "^NDX"
    },
    {
      "symbol": "DJI",
      "name": "Dow Jones",
      "yahoo": "^DJI"
    },
    {
      "symbol": "SX5E",
      "name": "Euro Stoxx 50",
      "yahoo": "^STOXX50E"
    },
    {
      "symbol": "DAX",
      "name": "DAX",
      "yahoo": "^GDAXI"
    },
    {
      "symbol": "CAC",
      "name": "CAC 40",
      "yahoo": "^FCHI"
    },
    {
      "symbol": "UKX",
      "name": "FTSE 100",
      "yahoo": "^FTSE"
    },
    {
      "symbol": "SMI",
      "name": "SMI",
      "yahoo": "^SSMI"
    },
    {
      "symbol": "NKX",
      "name": "Nikkei 225",
      "yahoo": "^N225"
    },
    {
      "symbol": "HSI",
      "name": "Hang Seng",
      "yahoo": "^HSI"
    }
  ],
  "bonds": [
    {
      "country": "US",
      "tenor": "10Y",
      "fred": "DGS10"
    },
    {
      "country": "US",
      "tenor": "3M",
      "fred": "DGS3MO"
    },
    {
      "country": "DE",
      "tenor": "10Y",
      "bundesbank": "D.I.ZST.ZI.EUR.S1311.B.A604.R10XX.R.A.A._Z._Z.A"
    },
    {
      "country": "DE",
      "tenor": "3M",
      "ecb": "YC.B.U2.EUR.4F.G_N_A.SV_C_YM.SR_3M"
    }
  ],
  "cb_rates": [
    {
      "country": "US",
      "label": "FED",
      "fred": "DFEDTARU"
    },
    {
      "country": "DE",
      "label": "ECB",
      "fred": "ECBDFR"
    }
  ],
  "series": [
    {
      "id": "us-cpi-yoy",
      "name": "US CPI YoY %",
      "fred": "CPIAUCSL",
      "unit": "%",
      "transform": "yoy"
    },
    {
      "id": "us-core-cpi-yoy",
      "name": "US Core CPI YoY %",
      "fred": "CPILFESL",
      "unit": "%",
      "transform": "yoy"
    },
    {
      "id": "us-pce-yoy",
      "name": "US PCE YoY %",
      "fred": "PCEPI",
      "unit": "%",
      "transform": "yoy"
    },
    {
      "id": "us-nfp",
      "name": "US Non-Farm Payrolls Δk",
      "fred": "PAYEMS",
      "unit": "k",
      "transform": "diff"
    },
    {
      "id": "us-unemployment",
      "name": "US Unemployment %",
      "fred": "UNRATE",
      "unit": "%",
      "transform": "none"
    },
    {
      "id": "us-gdp",
      "name": "US Real GDP QoQ SAAR %",
      "fred": "A191RL1Q225SBEA",
      "unit": "%",
      "transform": "none"
    },
    {
      "id": "us-retail",
      "name": "US Retail Sales MoM %",
      "fred": "RSAFS",
      "unit": "%",
      "transform": "pct_prev"
    },
    {
      "id": "us-fed-rate",
      "name": "Fed Funds Target Upper %",
      "fred": "DFEDTARU",
      "unit": "%",
      "transform": "none"
    },
    {
      "id": "ez-hicp-yoy",
      "name": "EZ HICP YoY %",
      "fred": "CP0000EZ19M086NEST",
      "unit": "%",
      "transform": "yoy"
    },
    {
      "id": "ez-unemployment",
      "name": "EZ Unemployment %",
      "fred": "LRHUTTTTEZM156S",
      "unit": "%",
      "transform": "none"
    },
    {
      "id": "ez-gdp",
      "name": "EZ Real GDP QoQ %",
      "fred": "CLVMEURSCAB1GQEA19",
      "unit": "%",
      "transform": "pct_prev"
    },
    {
      "id": "ez-ecb-rate",
      "name": "ECB Deposit Rate %",
      "fred": "ECBDFR",
      "unit": "%",
      "transform": "none"
    }
  ],
  "cycle_series": [
    {
      "id": "usrec",
      "name": "NBER Recession",
      "unit": "idx",
      "fred": "USREC",
      "hidden": true
    },
    {
      "id": "vix",
      "name": "VIX",
      "unit": "idx",
      "fred": "VIXCLS"
    },
    {
      "id": "vxn",
      "name": "VXN (Nasdaq vol)",
      "unit": "idx",
      "fred": "VXNCLS"
    },
    {
      "id": "pc-total",
      "name": "Put/Call total",
      "unit": "ratio",
      "cboe": "TOTAL PUT/CALL RATIO"
    },
    {
      "id": "pc-equity",
      "name": "Put/Call equity",
      "unit": "ratio",
      "cboe": "EQUITY PUT/CALL RATIO"
    },
    {
      "id": "aaii-spread",
      "name": "AAII bull-bear spread",
      "unit": "pts",
      "aaii": "bull_bear_spread"
    },
    {
      "id": "cyc-def",
      "name": "Cyclicals vs defensives",
      "unit": "ratio",
      "yahoo_ratio": [
        "XLY",
        "XLP"
      ]
    },
    {
      "id": "dax-smi",
      "name": "DAX vs SMI",
      "unit": "ratio",
      "yahoo_ratio": [
        "^GDAXI",
        "^SSMI"
      ]
    },
    {
      "id": "small-large",
      "name": "Small vs large (IWM/SPY)",
      "unit": "ratio",
      "yahoo_ratio": [
        "IWM",
        "SPY"
      ]
    },
    {
      "id": "gold-silver",
      "name": "Gold vs silver",
      "unit": "ratio",
      "yahoo_ratio": [
        "GC=F",
        "SI=F"
      ]
    },
    {
      "id": "spw-spx",
      "name": "Equal-weight vs SPX",
      "unit": "ratio",
      "yahoo_ratio": [
        "RSP",
        "SPY"
      ]
    },
    {
      "id": "ism-pmi",
      "name": "ISM Manufacturing PMI",
      "unit": "idx",
      "dbnomics": "ISM/pmi/pm",
      "valid_range": [
        20,
        80
      ]
    },
    {
      "id": "ism-svc",
      "name": "ISM Services PMI",
      "unit": "idx",
      "dbnomics": "ISM/nm-pmi/pm",
      "valid_range": [
        20,
        80
      ]
    },
    {
      "id": "oecd-cli-us",
      "name": "OECD CLI US",
      "unit": "idx",
      "oecd": "OECD.SDD.STES,DSD_STES@DF_CLI,4.1/USA.M.LI...AA...H"
    },
    {
      "id": "oecd-cli-ea",
      "name": "OECD CLI Europe (G4E)",
      "unit": "idx",
      "oecd": "OECD.SDD.STES,DSD_STES@DF_CLI,4.1/G4E.M.LI...AA...H"
    },
    {
      "id": "claims",
      "name": "Initial jobless claims",
      "unit": "k",
      "fred": "ICSA"
    },
    {
      "id": "jolts",
      "name": "Job openings (JOLTS)",
      "unit": "k",
      "fred": "JTSJOL"
    },
    {
      "id": "trucks",
      "name": "Heavy truck sales",
      "unit": "m",
      "fred": "HTRUCKSSAAR"
    },
    {
      "id": "umich",
      "name": "UMich consumer sentiment",
      "unit": "idx",
      "fred": "UMCSENT"
    },
    {
      "id": "m2-yoy",
      "name": "M2 YoY",
      "unit": "%",
      "fred": "M2SL",
      "transform": "yoy"
    },
    {
      "id": "m2-velocity",
      "name": "M2 velocity",
      "unit": "ratio",
      "fred": "M2V"
    },
    {
      "id": "breakeven-10y",
      "name": "10Y breakeven",
      "unit": "%",
      "fred": "T10YIE"
    },
    {
      "id": "infl-5y5y",
      "name": "5y5y fwd inflation",
      "unit": "%",
      "fred": "T5YIFR"
    },
    {
      "id": "real-10y",
      "name": "10Y real rate (TIPS)",
      "unit": "%",
      "fred": "DFII10"
    },
    {
      "id": "usd-broad",
      "name": "USD broad index",
      "unit": "idx",
      "fred": "DTWEXBGS"
    },
    {
      "id": "t10y3m",
      "name": "US 10Y-3M curve",
      "unit": "%",
      "fred": "T10Y3M"
    },
    {
      "id": "t10y2y",
      "name": "US 10Y-2Y curve",
      "unit": "%",
      "fred": "T10Y2Y"
    },
    {
      "id": "ig-oas",
      "name": "US IG OAS",
      "unit": "%",
      "fred": "BAMLC0A0CM"
    },
    {
      "id": "hy-oas",
      "name": "US HY OAS",
      "unit": "%",
      "fred": "BAMLH0A0HYM2"
    },
    {
      "id": "eu-hy-oas",
      "name": "Euro HY OAS",
      "unit": "%",
      "fred": "BAMLHE00EHYIOAS"
    },
    {
      "id": "bbb-oas",
      "name": "US BBB OAS",
      "unit": "%",
      "fred": "BAMLC0A4CBBB"
    },
    {
      "id": "ccc-oas",
      "name": "US CCC OAS",
      "unit": "%",
      "fred": "BAMLH0A3HYC"
    },
    {
      "id": "nfci",
      "name": "Chicago Fed NFCI",
      "unit": "idx",
      "fred": "NFCI"
    },
    {
      "id": "bank-lending",
      "name": "Bank loans & leases YoY",
      "unit": "%",
      "fred": "LOANS",
      "transform": "yoy"
    },
    {
      "id": "corp-profits",
      "name": "Corporate profits YoY",
      "unit": "%",
      "fred": "CP",
      "transform": "yoy"
    },
    {
      "id": "cot-vix",
      "name": "VIX net non-commercial",
      "unit": "contracts",
      "cftc": "1170E1"
    },
    {
      "id": "cot-crude",
      "name": "Crude net non-commercial",
      "unit": "contracts",
      "cftc": "067651"
    },
    {
      "id": "cot-usd",
      "name": "USD idx net non-commercial",
      "unit": "contracts",
      "cftc": "098662"
    },
    {
      "id": "cot-gbp",
      "name": "GBP net non-commercial",
      "unit": "contracts",
      "cftc": "096742"
    }
  ],
  "cycle_tabs": [
    {
      "id": "risk",
      "label": "RISK",
      "panels": [
        {
          "title": "VOLATILITY & HEDGING",
          "rows": [
            {
              "series": "vix",
              "overlay": "t10y2y"
            },
            {
              "series": "vxn"
            },
            {
              "series": "pc-total"
            },
            {
              "series": "pc-equity"
            }
          ]
        },
        {
          "title": "SENTIMENT & ROTATION",
          "rows": [
            {
              "series": "aaii-spread"
            },
            {
              "series": "cyc-def"
            },
            {
              "series": "dax-smi"
            },
            {
              "series": "small-large"
            },
            {
              "series": "gold-silver"
            },
            {
              "series": "spw-spx"
            }
          ]
        }
      ]
    },
    {
      "id": "econ",
      "label": "ECON",
      "panels": [
        {
          "title": "SURVEYS & LEADING",
          "rows": [
            {
              "series": "ism-pmi",
              "overlay": "t10y2y"
            },
            {
              "series": "ism-svc"
            },
            {
              "series": "oecd-cli-us"
            },
            {
              "series": "oecd-cli-ea"
            },
            {
              "series": "umich"
            }
          ]
        },
        {
          "title": "ACTIVITY & MONEY",
          "rows": [
            {
              "series": "claims"
            },
            {
              "series": "jolts"
            },
            {
              "series": "trucks"
            },
            {
              "series": "m2-yoy"
            },
            {
              "series": "m2-velocity"
            },
            {
              "series": "usd-broad"
            }
          ]
        },
        {
          "title": "INFLATION & RATES",
          "rows": [
            {
              "series": "breakeven-10y"
            },
            {
              "series": "infl-5y5y"
            },
            {
              "series": "real-10y"
            }
          ]
        }
      ]
    },
    {
      "id": "credit",
      "label": "CREDIT",
      "panels": [
        {
          "title": "CURVE",
          "rows": [
            {
              "series": "t10y3m",
              "overlay": "vix"
            },
            {
              "series": "t10y2y"
            }
          ]
        },
        {
          "title": "SPREADS & CONDITIONS",
          "rows": [
            {
              "series": "ig-oas"
            },
            {
              "series": "hy-oas",
              "overlay": "ism-pmi"
            },
            {
              "series": "eu-hy-oas"
            },
            {
              "series": "bbb-oas"
            },
            {
              "series": "ccc-oas"
            },
            {
              "series": "nfci"
            },
            {
              "series": "bank-lending"
            }
          ]
        }
      ]
    },
    {
      "id": "profit",
      "label": "PROFIT",
      "panels": [
        {
          "title": "PROFIT CYCLE",
          "rows": [
            {
              "series": "corp-profits",
              "overlay": "ism-pmi"
            }
          ]
        }
      ]
    },
    {
      "id": "pos",
      "label": "POS",
      "panels": [
        {
          "title": "CFTC NET NON-COMMERCIAL",
          "rows": [
            {
              "series": "cot-vix",
              "overlay": "vix"
            },
            {
              "series": "cot-crude"
            },
            {
              "series": "cot-usd",
              "overlay": "usd-broad"
            },
            {
              "series": "cot-gbp"
            }
          ]
        }
      ]
    }
  ],
  "calendar_map": [
    {
      "country": "USD",
      "match": "Core CPI",
      "series": "us-core-cpi-yoy"
    },
    {
      "country": "USD",
      "match": "CPI",
      "series": "us-cpi-yoy"
    },
    {
      "country": "USD",
      "match": "Core PCE",
      "series": "us-pce-yoy"
    },
    {
      "country": "USD",
      "match": "Non-Farm",
      "series": "us-nfp"
    },
    {
      "country": "USD",
      "match": "Unemployment",
      "series": "us-unemployment"
    },
    {
      "country": "USD",
      "match": "GDP",
      "series": "us-gdp"
    },
    {
      "country": "USD",
      "match": "Retail Sales",
      "series": "us-retail"
    },
    {
      "country": "USD",
      "match": "Federal Funds Rate",
      "series": "us-fed-rate"
    },
    {
      "country": "EUR",
      "match": "Core CPI",
      "series": "ez-hicp-yoy"
    },
    {
      "country": "EUR",
      "match": "CPI",
      "series": "ez-hicp-yoy"
    },
    {
      "country": "EUR",
      "match": "Unemployment",
      "series": "ez-unemployment"
    },
    {
      "country": "EUR",
      "match": "GDP",
      "series": "ez-gdp"
    },
    {
      "country": "EUR",
      "match": "Main Refinancing Rate",
      "series": "ez-ecb-rate"
    }
  ],
  "feeds": [
    {
      "name": "FT",
      "url": "https://www.ft.com/rss/home"
    },
    {
      "name": "CNBC",
      "url": "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100003114"
    },
    {
      "name": "MarketWatch",
      "url": "https://feeds.content.dowjones.io/public/rss/mw_topstories"
    },
    {
      "name": "ECB",
      "url": "https://www.ecb.europa.eu/rss/press.html"
    },
    {
      "name": "Fed",
      "url": "https://www.federalreserve.gov/feeds/press_all.xml"
    }
  ],
  "zyfai_base": "https://defiapi.zyf.ai/api/v2/opportunities",
  "midnight_base": "https://api.morpho.org/v0/midnight",
  "defi": {
    "asset": "USDC",
    "strategies": [
      {
        "id": "safe",
        "label": "Conservative"
      },
      {
        "id": "degen",
        "label": "Moderate"
      },
      {
        "id": "async",
        "label": "Dynamic"
      }
    ],
    "chains": [
      {
        "id": 8453,
        "name": "Base",
        "usdc": "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
      },
      {
        "id": 1,
        "name": "Ethereum",
        "usdc": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
      },
      {
        "id": 42161,
        "name": "Arbitrum",
        "usdc": "0xaf88d065e77c8cc2239327c5edb3a432268e5831"
      }
    ],
    "midnight_chains": [
      8453
    ],
    "token_symbols": {
      "0xcbb7c0000ab88b473b1f5afd9ef808440eed33bf": "cbBTC",
      "0x4200000000000000000000000000000000000006": "WETH"
    },
    "morpho_graphql": "https://blue-api.morpho.org/graphql",
    "morpho_first": 25
  },
  "refs": {
    "aave": [
      {
        "chain": "BASE",
        "rpc": "https://base-rpc.publicnode.com",
        "pool": "0xa238dd80c259a72e81d7e4664a9801593f98d1c5",
        "symbol": "USDC",
        "asset": "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
      },
      {
        "chain": "ETH",
        "rpc": "https://ethereum-rpc.publicnode.com",
        "pool": "0x87870bca3f3fd6335c3f4ce8392d69350b4fa4e2",
        "symbol": "USDC",
        "asset": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
      },
      {
        "chain": "ETH",
        "rpc": "https://ethereum-rpc.publicnode.com",
        "pool": "0x87870bca3f3fd6335c3f4ce8392d69350b4fa4e2",
        "symbol": "USDT",
        "asset": "0xdac17f958d2ee523a2206206994597c13d831ec7"
      },
      {
        "chain": "ARB",
        "rpc": "https://arb1.arbitrum.io/rpc",
        "pool": "0x794a61358d6845594f94dc1db02a252b5b4814ad",
        "symbol": "USDC",
        "asset": "0xaf88d065e77c8cc2239327c5edb3a432268e5831"
      },
      {
        "chain": "ARB",
        "rpc": "https://arb1.arbitrum.io/rpc",
        "pool": "0x794a61358d6845594f94dc1db02a252b5b4814ad",
        "symbol": "USDT",
        "asset": "0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9"
      }
    ],
    "llama_chart": [
      {
        "pool": "7e0661bf-8cf3-45e6-9424-31916d4c7b84",
        "series": "aave-base-usdc-supply"
      },
      {
        "pool": "aa70268e-4b52-42bf-a116-608b370f9501",
        "series": "aave-eth-usdc-supply"
      },
      {
        "pool": "f981a304-bb6c-45b8-b0c5-fd2f515ad23a",
        "series": "aave-eth-usdt-supply"
      },
      {
        "pool": "d9fa8e14-0447-4207-9ae8-7810199dfa1f",
        "series": "aave-arb-usdc-supply"
      },
      {
        "pool": "3a6cc030-738d-4e19-8a40-e63e9c4d5a6f",
        "series": "aave-arb-usdt-supply"
      }
    ],
    "pendle": [
      {
        "chain_id": 8453,
        "address": "0xa97bb0de338b23c088dba9bf8c948da726e49033",
        "implied_id": "pendle-pt-cbbtc-usdc",
        "implied_label": "PENDLE PT",
        "underlying_id": "pendle-underlying-cbbtc-usdc",
        "underlying_label": "PENDLE UNDERLY"
      }
    ],
    "funding": [
      {
        "symbol": "BTCUSDT",
        "id": "funding-binance-btc",
        "label": "BTC FUND ANN"
      }
    ]
  }
};
